# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('alias', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=150)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
